### ISSUE TITLE
Entrepôt requires a WordPress ready archive into the release's download section.

### ISSUE THREAD

**Issue by imath** [lriaudel/wp-tunning#3]
Hello,

You forgot an important step, i just tested installing your plugin using the Entrepôt and it fails because you are not adding a WordPress ready archive named `wp-tuning.zip` into the download section of your plugin's releases.

See the [documentation](https://github.com/imath/entrepot/wiki/02-Plugin-Author-Guide#binding-the-wordpress-ready-plugins-archive-file-to-your-release) for more informations about it.

Moreover, i advise you to use a [semantic versioning](https://semver.org) eg: 1.0.0 instead of 1.0. It's best for Entrepôt's upgrade feature to work properly.

**Comment by lriaudel** [comment]
Hi,
The differents releases is here : https://github.com/lriaudel/wp-tuning/releases

**Comment by imath** [comment]
Je vais l'écrire en français : je sais où sont tes releases!! 

si tu veux que ça fonctionne, il faut que tu mettes un fichier zip s'intitulant **wp-tuning.zip** dans les downloads de tes releases autrement ça ne fonctionnera pas.

Regarde dans l'encadré rouge comment je fais pour l'extension WordCamp Talks

![wordpress-archive](https://user-images.githubusercontent.com/1834524/34909210-b340b62c-f89c-11e7-9ba1-89a152599339.png)

**Comment by lriaudel** [comment]
OK, je n'avais pas vu.
J'ai un autre souci, en fait je pensais avoir réglé le souci du slug du repo WP, mais ce n'est pas le cas. Il faut que je renomme sans doute.

**Comment by imath** [comment]
Effectivement, si un repo sur WordPress.org a pour slug `wp-tuning` je te conseille de changer de slug  et de refaire une PR pour supprimer `/repositories/wp-tuning.json` et ajouter le nouveau repo. Pas d'urgence, je ne publierai la prochaine version de l'Entrepôt que lorsque tu seras prêt ;)

Pour info depuis les settings de ce repo tu peux tout à fait changer de nom.
